name: Run unit tests

on:
  push:
    branches:
      - main
      - update_build_config
    paths-ignore:
      - 'docs/**'
      - 'MANIFEST.in'
      - 'README.rst'
      - 'THANKS.rst'
      - 'COPYING.txt'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches:
      - main

jobs:
  tests:
    continue-on-error: true
    strategy:
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'windows-2022'
        python-version:
          - '3.12'
          - '3.13'
        extra-doctest-ignore:
          - ''
        # The OrderedDict __str__ method changed in Python 3.12 so doctests in the ytools.py module will fail
        # on older versions of Python.
        include:
          - os: 'ubuntu-24.04'
            python-version: '3.10'
            extra-doctest-ignore: '--ignore=pyyeti/ytools.py'
          - os: 'windows-2022'
            python-version: '3.10'
            extra-doctest-ignore: '--ignore=pyyeti/ytools.py'
          - os: 'ubuntu-24.04'
            python-version: '3.11'
            extra-doctest-ignore: '--ignore=pyyeti/ytools.py'
          - os: 'windows-2022'
            python-version: '3.11'
            extra-doctest-ignore: '--ignore=pyyeti/ytools.py'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install -v .[dev]
    - name: Verify c_rain module successfully compiled
      shell: bash
      run: |
        python -c "from pyyeti.rainflow import c_rain; print(c_rain.__file__)"
    - name: Test with pytest
      run: |
        python -m pytest --cov --doctest-modules pyyeti --ignore=pyyeti/tests ${{ matrix.extra-doctest-ignore}}
        python -m pytest --cov --cov-append pyyeti/tests