name: Build wheels

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "MANIFEST.in"
      - "README.rst"
      - "THANKS.rst"
      - "COPYING.txt"
      - ".gitignore"
      - ".gitattributes"
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: write

jobs:
  build_wheels:
    name: "Build wheels: ${{ matrix.os }} ${{ matrix.arch }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source dist and upload all
    runs-on: ubuntu-latest
    needs: [build_wheels]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies and build sdist
        run: |
          export PYTHON_VENV=`mktemp -d`
          python -m venv $PYTHON_VENV --upgrade-deps
          $PYTHON_VENV/bin/python -c "import sys; print(sys.executable)"
          $PYTHON_VENV/bin/pip install -v build
          $PYTHON_VENV/bin/python -m build -s .
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          merge-multiple: true
          path: dist/
      - name: Upload wheels and sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-and-sdist
          path: dist/
